[package]
name = "google_pagespeedonline_v1"
version = "0.1.0"
authors = ["Glenn Griffin <ggriffiniii@gmail.com"]
edition = "2018"
# for now, let's not even accidentally publish these
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
reqwest = "0.9"
field_selector = { git = "https://github.com/ggriffiniii/google-apis" }
mime = "0.3"
textnonce = "0.6"
yup-oauth2 = "3"
tokio = "0.1"
percent-encoding = "2"
radix64 = "0.6"
